export const browserCoreExamples = [
  "floo browser status",
  "floo browser start",
  "floo browser stop",
  "floo browser tabs",
  "floo browser open https://example.com",
  "floo browser focus abcd1234",
  "floo browser close abcd1234",
  "floo browser screenshot",
  "floo browser screenshot --full-page",
  "floo browser screenshot --ref 12",
  "floo browser snapshot",
  "floo browser snapshot --format aria --limit 200",
  "floo browser snapshot --efficient",
  "floo browser snapshot --labels",
];

export const browserActionExamples = [
  "floo browser navigate https://example.com",
  "floo browser resize 1280 720",
  "floo browser click 12 --double",
  'clawdbot browser type 23 "hello" --submit',
  "floo browser press Enter",
  "floo browser hover 44",
  "floo browser drag 10 11",
  "floo browser select 9 OptionA OptionB",
  "floo browser upload /tmp/file.pdf",
  'clawdbot browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "floo browser dialog --accept",
  'clawdbot browser wait --text "Done"',
  "floo browser evaluate --fn '(el) => el.textContent' --ref 7",
  "floo browser console --level error",
  "floo browser pdf",
];
